name: Vitest

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm ci
      - run: npm run build
      - run: npm run test