on:
  push:
    tags:
      - "*"
  workflow_dispatch:

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1

      - name: Setup
        run: |
          bun install --frozen-lockfile
          bun run build

      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          packagePath: "./packages/ramattra-vscode"
          pat: ${{ secrets.OPEN_VSX_TOKEN }}